openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://h2o-experts-server.onrender.com
paths:
  /users/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
